services:
  - type: web
    name: freight-payroll-backend
    runtime: node
    rootDir: packages/backend
    buildCommand: npm install && prisma migrate deploy && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
